name: build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: build
        run: |
          npm install -g pnpm
          pnpm i
          npm run build

      - name: deploy
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "chore: deploy docs"
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
